#!/bin/bash

echo "🔧 MONITORING STACK ACCESS URLs"
echo "================================"
echo ""
echo "📊 Grafana Dashboard:"
echo "   URL: http://localhost:3000"
echo "   Login: admin / admin"
echo ""
echo "📈 Prometheus Metrics:"
echo "   URL: http://localhost:9090"
echo ""
echo "🔍 Jaeger Tracing:"
echo "   URL: http://localhost:16686"
echo ""
echo "🚀 RAG API (se rodando):"
echo "   URL: http://localhost:8000"
echo "   Health: http://localhost:8000/health"
echo "   Metrics: http://localhost:8000/metrics"
echo ""
echo "💡 Para abrir no navegador:"
echo "   open http://localhost:3000  # Grafana"
echo "   open http://localhost:9090  # Prometheus"
echo "   open http://localhost:16686 # Jaeger"
echo ""
echo "🔧 Para parar os serviços:"
echo "   docker compose -f docker-compose-fixed.yml down"
echo ""
echo "🔧 Para ver logs:"
echo "   docker compose -f docker-compose-fixed.yml logs -f"
